when:
  - event: push
    branch: main

steps:
  - name: build-go
    image: golang:latest
    environment:
      GOOS: linux
      GOARCH: amd64
    commands:
      - go mod tidy
      - cd cmd/phone
      - go build -o ../../phone

  - name: deploy
    image: docker:24.0.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - ssh -i /ssh/external.law.local -o StrictHostKeyChecking=no -fNL /tmp/docker.sock:/var/run/docker.sock aidan@external.law.local
      - export DOCKER_HOST=unix:///tmp/docker.sock
      - docker build -t phone:local .
      - docker image prune -f --filter "dangling=true"
      - docker stop phone || true
      - docker rm phone || true
      - >
        docker run -d
        --name phone
        --restart always
        -v /server/phone/config.json:/app/config.json
        -v /server/phone/crt:/app/crt
        -p 192.168.1.215:443:443
        phone:local

