steps:
  - name: build
    image: golang:latest
    environment:
      GOOS: linux
      GOARCH: amd64
    commands:
      - go mod tidy
      - go build -o seacow-phone
    when:
      - branch: [main]

  - name: docker
    image: docker:24.0.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t seacow-phone:local .
    when:
      - branch: [main]
