when:
  - event: push
    branch: main

steps:
  - name: build-go
    image: golang:latest
    environment:
      GOOS: linux
      GOARCH: amd64
    commands:
      - go mod tidy
      - cd cmd/phone
      - go build -o ../../phone

  - name: build-docker
    image: docker:24.0.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t phone:local .
      - docker image prune -f --filter "dangling=true"

